/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import client.Client;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author Dell
 */
public class ChatWindow extends javax.swing.JFrame {

    public Client client;
    public GridLayout c1;
    public static int oldcount = 0;
    public static int chatoldcount = 0;
    public static int rows = 2;
    public boolean isrun = false;
    Thread updateThread;

    /**
     * Creates new form ChatWindow
     */
    public ChatWindow() {
        initComponents();
        isrun = true;
        oldcount = 0;
        chatoldcount = 0;
        chatpanel();
        client = new Client();
        updateUI();
        txtusername.setText(ChatLogin.loginid);
        this.setTitle(SelectThreadPage.threadname);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        activepanel1 = new javax.swing.JPanel();
        scrl = new javax.swing.JScrollPane();
        activepanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnsend = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtmsg = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnlogout = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        txtusername = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        msgpanel = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 1, true));

        activepanel1.setBackground(new java.awt.Color(255, 255, 204));
        activepanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        activepanel.setBackground(new java.awt.Color(102, 102, 102));
        activepanel.setMinimumSize(new java.awt.Dimension(100, 500));
        activepanel.setPreferredSize(new java.awt.Dimension(100, 500));

        javax.swing.GroupLayout activepanelLayout = new javax.swing.GroupLayout(activepanel);
        activepanel.setLayout(activepanelLayout);
        activepanelLayout.setHorizontalGroup(
            activepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
        );
        activepanelLayout.setVerticalGroup(
            activepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        scrl.setViewportView(activepanel);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("Active List");

        javax.swing.GroupLayout activepanel1Layout = new javax.swing.GroupLayout(activepanel1);
        activepanel1.setLayout(activepanel1Layout);
        activepanel1Layout.setHorizontalGroup(
            activepanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrl, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
            .addGroup(activepanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        activepanel1Layout.setVerticalGroup(
            activepanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activepanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnsend.setBackground(new java.awt.Color(0, 153, 153));
        btnsend.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsend.setForeground(new java.awt.Color(255, 255, 255));
        btnsend.setText("Send");
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });

        txtmsg.setColumns(20);
        txtmsg.setRows(5);
        jScrollPane2.setViewportView(txtmsg);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        btnlogout.setBackground(new java.awt.Color(255, 102, 102));
        btnlogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        btnback.setBackground(new java.awt.Color(0, 204, 153));
        btnback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        txtusername.setFont(new java.awt.Font("Source Sans Pro", 1, 14)); // NOI18N
        txtusername.setForeground(new java.awt.Color(51, 51, 51));
        txtusername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtusername.setText("User Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(txtusername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(149, 149, 149)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(432, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlogout, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnback, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        msgpanel.setBackground(new java.awt.Color(102, 102, 102));
        msgpanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane3.setViewportView(msgpanel);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btnsend, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsend, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(activepanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(activepanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed
        send();
    }//GEN-LAST:event_btnsendActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        try {
            isrun = false;
            updateThread.join();
            this.dispose();
            new SelectThreadPage().setVisible(true);
        } catch (InterruptedException ex) {
            Logger.getLogger(ChatWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        logout();
    }//GEN-LAST:event_btnlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel activepanel;
    private javax.swing.JPanel activepanel1;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnsend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane msgpanel;
    private javax.swing.JScrollPane scrl;
    private javax.swing.JTextArea txtmsg;
    private javax.swing.JLabel txtusername;
    // End of variables declaration//GEN-END:variables

    private void updateUI() {
        c1 = new GridLayout(1, 0);

        updateThread = new Thread(new Runnable() {
            @Override
            public void run() {
                while (isrun) {
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(ChatWindow.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    showActiveUsers();
                    loadchat();
                }
            }

        });
        updateThread.start();
    }

    public void showActiveUsers() {
        ArrayList<String> activelist = (ArrayList<String>) client.getActivelist();

        int count = activelist.size();
        if (oldcount != count) {
            activepanel.removeAll();
            activepanel.revalidate();
            activepanel.repaint();

            if ((activelist.size() > 0)) {
                for (String al : activelist) {
                    String[] data = al.split("#");
                    JLabel b = new JLabel(data[0] + "");
                    b.setBounds(20, rows * 20, 100, 20);
                    b.setForeground(Color.GREEN);

                    b.setFont(new Font("Serif", Font.BOLD, 16));
                    activepanel.add(b);
                    rows++;
                }

            }
            oldcount = count;
            rows = 2;
        }
    }

    private void send() {
        Date dNow = new Date();
        SimpleDateFormat ft = new SimpleDateFormat("yyyy.MM.dd/hh:mm:ss");
        String loginid = ChatLogin.loginid;
        String date = ft.format(dNow);
        String message = txtmsg.getText();

        if (!(loginid.equals("") & date.equals("") & message.equals(""))) {
            boolean isok = client.broadcast(loginid, message, date, SelectThreadPage.threadname);
            if (isok) {

            } else {

            }
        }
    }

    private void chatpanel() {
        // msgpanel.setLineWrap(true);
        //msgpanel.setWrapStyleWord(true);
        msgpanel.setEditable(false);
        //msgpanel.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    }

    private void loadchat() {
        ArrayList<String> msglist = (ArrayList<String>) client.receive();
        int ncount = msglist.size();
        for (String m : msglist) {
            System.out.println(m);
        }
        if (chatoldcount != ncount) {
            msgpanel.setText("");
            StyledDocument doc = msgpanel.getStyledDocument();
            Style style = msgpanel.addStyle("ok", null);
            StyleConstants.setForeground(style, Color.blue);
            StyleConstants.setFontSize(style, 10);
            StyleConstants.setSpaceAbove(style, 4);

            for (String ml : msglist) {
                String[] data = ml.split("#");
                String thread = data[3];
                /*check if all messages are for this chat*/
                if (thread.equals(SelectThreadPage.threadname)) {
                    /*check if message comes from this user*/
                    if (data[0].equals(ChatLogin.loginid)) {
                        try {
                            //doc.insertString(doc.getLength(), "send by " + data[0] + " at " + data[2] + "\n", style);
                            StyleConstants.setForeground(style, Color.GREEN);
                            StyleConstants.setFontSize(style, 14);
                            StyleConstants.setBold(style, true);
                            doc.insertString(doc.getLength(), data[1] + "\n\n", style);
                            StyleConstants.setForeground(style, Color.BLUE);
                            StyleConstants.setFontSize(style, 10);
                            StyleConstants.setBold(style, false);
                            //StyleConstants.setForeground(style, Color.red);
                            // msgpanel.append("send by " + data[0] + " at " + data[2] + "\n" + data[1] + "\n\n");
                            //doc.insertString(doc.getLength(),"send by "+data[0], style);
                        } catch (BadLocationException ex) {
                            Logger.getLogger(ChatWindow.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    } else {/*message is from diffrent user*/
                        try {
                            StyleConstants.setForeground(style, Color.RED);
                            doc.insertString(doc.getLength(), "send by " + data[0] + " at " + data[2] + "\n", style);
                            StyleConstants.setForeground(style, Color.blue);
                            StyleConstants.setFontSize(style, 14);
                            StyleConstants.setBold(style, true);
                            doc.insertString(doc.getLength(), data[1] + "\n\n", style);
                            //StyleConstants.setForeground(style, Color.red);
                            StyleConstants.setFontSize(style, 10);
                            StyleConstants.setBold(style, false);

                        } catch (BadLocationException ex) {
                            Logger.getLogger(ChatWindow.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
            chatoldcount = ncount;

        }

    }

    private void logout() {
        boolean islogout = client.signout(ChatLogin.loginid);
        if (islogout) {
            try {
                isrun = false;
                updateThread.join();
                this.dispose();
                new ChatLogin().setVisible(true);
            } catch (InterruptedException ex) {
                Logger.getLogger(ChatWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {

        }
    }
}
