/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import client.Client;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NThread;

/**
 *
 * @author Dell
 */
public class SelectThreadPage extends javax.swing.JFrame {

    public Client client;
    public static int oldcount = 0;
    private boolean isrun = false;
    private DefaultTableModel tbm;
    public static String threadname = "";
    Thread loadtable;

    /**
     * Creates new form SelectThreadPage
     */
    public SelectThreadPage() {
        initComponents();
        tbm = (DefaultTableModel) tblthread.getModel();
        isrun = true;
        oldcount = 0;
        client = new Client();
        loadThread();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblthread = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        btnEditselected = new javax.swing.JButton();
        btnCreatenew = new javax.swing.JButton();
        btnchatwindow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 1, true));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblthread.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Last Edited", "By"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblthread);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnEditselected.setBackground(new java.awt.Color(102, 153, 255));
        btnEditselected.setText("Edit Selected");
        btnEditselected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditselectedActionPerformed(evt);
            }
        });

        btnCreatenew.setBackground(new java.awt.Color(0, 204, 153));
        btnCreatenew.setText("Create New");
        btnCreatenew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatenewActionPerformed(evt);
            }
        });

        btnchatwindow.setBackground(new java.awt.Color(255, 102, 102));
        btnchatwindow.setText("Chat");
        btnchatwindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchatwindowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEditselected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(39, 39, 39)
                        .addComponent(btnCreatenew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(btnchatwindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(170, 170, 170))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnchatwindow, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditselected, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreatenew, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditselectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditselectedActionPerformed
        int col = 0;
        int row = tblthread.getSelectedRow();
        System.out.println(row);
        if (row != -1) {
            try {
                isrun = false;
                loadtable.join();
                threadname = tbm.getValueAt(row, col).toString();
                new EditThreadsPage().setVisible(true);
                this.dispose();
            } catch (InterruptedException ex) {
                Logger.getLogger(SelectThreadPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            //please selected a thread 
            JOptionPane.showMessageDialog(this, "Please select a thread.", "Alert", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEditselectedActionPerformed

    private void btnCreatenewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatenewActionPerformed
        try {
            isrun = false;
            loadtable.join();
            this.dispose();
            new AddThreadPage().setVisible(true);
        } catch (InterruptedException ex) {
            Logger.getLogger(SelectThreadPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCreatenewActionPerformed

    private void btnchatwindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchatwindowActionPerformed

        goToChat();
    }//GEN-LAST:event_btnchatwindowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectThreadPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectThreadPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectThreadPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectThreadPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectThreadPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatenew;
    private javax.swing.JButton btnEditselected;
    private javax.swing.JButton btnchatwindow;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblthread;
    // End of variables declaration//GEN-END:variables

    private void loadThread() {
        loadtable = new Thread(new Runnable() {
            @Override
            public void run() {
                while (isrun) {
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(SelectThreadPage.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    generateTable();
                    System.out.println("running");
                }
            }
        });
        loadtable.start();
    }

    private void generateTable() {

        ArrayList<String> threadlist = (ArrayList<String>) client.getthreadList();
        int count = threadlist.size();
        if (threadlist.size() > 0) {

            if (oldcount != count) {
                System.out.println("loading table");
                tbm.setRowCount(0);
                int j = 0;
                for (String tl : threadlist) {
                    String[] data = tl.split("#");
                    NThread nt = new NThread(data[0], data[1], data[2]);

                    tbm.insertRow(j++, data);
                }
                oldcount = count;
            }
        } else {
            System.out.println("no threads");
        }

    }

    private void goToChat() {
        int col = 0;
        int row = tblthread.getSelectedRow();
        System.out.println(row);
        if (row != -1) {
            threadname = tbm.getValueAt(row, col).toString();
            if (!threadname.equals("")) {
                try {
                    //threadname="";
                    isrun = false;
                    loadtable.join();
                    this.dispose();
                    new ChatWindow().setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(SelectThreadPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

}
